name: Index to Neo4j

on:
  push:
    branches:
      - main

jobs:
  index:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          clean: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Install CodeToNeo4j
        run: ./.github/scripts/index-to-neo4j_install-codetoneo4j.sh

      - name: Run CodeToNeo4j
        env:
          NEO4J_URI: ${{ vars.NEO4J_URI }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          DIFF_BASE: ${{ github.event.before }}
        run: ./.github/scripts/index-to-neo4j_run-codetoneo4j.sh
